export const CARD_LIST_REQUEST = 'CARD_LIST_REQUEST';
export const CARD_LIST_SUCCESS = 'CARD_LIST_SUCCESS';
export const CARD_LIST_FAIL = 'CARD_LIST_FAIL';

export const CARD_DETAILS_REQUEST = 'CARD_DETAILS_REQUEST';
export const CARD_DETAILS_SUCCESS = 'CARD_DETAILS_SUCCESS';
export const CARD_DETAILS_FAIL = 'CARD_DETAILS_FAIL';
export const CARD_DETAILS_RESET = 'CARD_DETAILS_RESET';

export const CARD_DELETE_REQUEST = 'CARD_DELETE_REQUEST';
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS';
export const CARD_DELETE_FAIL = 'CARD_DELETE_FAIL';

export const CARD_CREATE_REQUEST = 'CARD_CREATE_REQUEST';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAIL = 'CARD_CREATE_FAIL';
export const CARD_CREATE_RESET = 'CARD_CREATE_RESET';

export const CARD_UPDATE_REQUEST = 'CARD_UPDATE_REQUEST';
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS';
export const CARD_UPDATE_FAIL = 'CARD_UPDATE_FAIL';
export const CARD_UPDATE_RESET = 'CARD_UPDATE_RESET';

export const CARD_SCRYFALL_REQUEST = 'CARD_SCRYFALL_REQUEST';
export const CARD_SCRYFALL_SUCCESS = 'CARD_SCRYFALL_SUCCESS';
export const CARD_SCRYFALL_FAIL = 'CARD_SCRYFALL_FAIL';
