export const SCRYFALL_CARD_REQUEST = 'SCRYFALL_CARD_REQUEST';
export const SCRYFALL_CARD_SUCCESS = 'SCRYFALL_CARD_SUCCESS';
export const SCRYFALL_CARD_FAIL = 'SCRYFALL_CARD_FAIL';
export const SCRYFALL_CARD_RESET = 'SCRYFALL_CARD_RESET';

export const SCRYFALL_EDITIONS_REQUEST = 'SCRYFALL_EDITIONS_REQUEST';
export const SCRYFALL_EDITIONS_SUCCESS = 'SCRYFALL_EDITIONS_SUCCESS';
export const SCRYFALL_EDITIONS_FAIL = 'SCRYFALL_EDITIONS_FAIL';

export const SCRYFALL_LIST_REQUEST = 'SCRYFALL_LIST_REQUEST';
export const SCRYFALL_LIST_SUCCESS = 'SCRYFALL_LIST_SUCCESS';
export const SCRYFALL_LIST_FAIL = 'SCRYFALL_LIST_FAIL';
